name: Linting and formatting with biome.js
on:
  push:
    branches:
      - '**'

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: node:22

    steps:
      - uses: actions/checkout@v3
      - run: npm ci

      - name: Run Eslint
        run: npm run lint
